export const CREATE_POKEMON = 'CREATE_POKEMON';

export const RETRIEVE_POKEMONS = 'RETRIEVE_POKEMONS';

export const RETRIEVE_A_POKEMON = 'RETRIEVE_A_POKEMON';

export const UPDATE_POKEMON = 'UPDATE_POKEMON';

export const DELETE_POKEMON = 'DELETE_POKEMON';